<a href="ProductData">Go back to previous page</a>
<form name="display_logs" method="get" action="Logs">
    Select Month:<br />
    <select name="month">
        <option value="null">--</option>
        <option value="01">January</option>
        <option value="02">February</option>
        <option value="03">March</option>
        <option value="04">April</option>
        <option value="05">May</option>
        <option value="06">June</option>
        <option value="07">July</option>
        <option value="08">August</option>
        <option value="09">September</option>
        <option value="10">October</option>
        <option value="11">November</option>
        <option value="12">December</option>
    </select><br />
    <input type="submit" value="View Log" size="12" name="submit"><br />
</form>